
/**************************************************************
 *	
 *	TITLESONG, 8 bit, 11025Hz,
 *	1 channel, 211680 bytes/channel
 *	Total Size: 1 * 211680 + 4 (header) = 211724 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Programming\C\cs2261\ThomasRistau_FinalProject\TITLESONG.wav
 *	Time-stamp: Sat Apr 18 18:39:45 2015
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 211680

extern const unsigned char TITLESONG[211680];

#endif /* __TITLESONGH__ */
